apiVersion: v1
kind: Service
metadata:
  name: hydra-server-service
spec:
  type: NodePort
  selector:
    app: hydra-server
  ports:
    - name: hydra
      protocol: TCP
      port: 4444
      targetPort: 4444
    - name: hydra-admin
      protocol: TCP
      port: 4445
      targetPort: 4445
