apiVersion: v1
kind: Service
metadata:
  name: login-consent-service
spec:
  type: NodePort
  selector:
    app: login-consent-app
  ports:
    - name: login-consent-port
      protocol: TCP
      port: 3000